export const GREEN = '#30C169'

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const CREATE_SONG_TABLE = 'CREATE_SONG_TABLE';
export const CREATE_SONG_TABLE_SUCCESS = 'CREATE_SONG_TABLE_SUCCESS';
export const CREATE_SONG_TABLE_FAILURE = 'CREATE_SONG_TABLE_FAILURE';

export const DROP_TABLES = 'DROP_TABLES';
export const DROP_TABLES_SUCESS = 'DROP_TABLES_SUCESS';
export const DROP_TABLES_FAILURE = 'DROP_TABLES_FAILURE';

export const ADD_SONG = 'ADD_SONG';
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS';
export const ADD_SONG_FAILURE = 'ADD_SONG_FAILURE';

export const CLEAR_CHANGED = 'CLEAR_CHANGED';
export const SELECT_SONG = 'SELECT_SONG';

export const GET_SONGS = 'GET_SONGS';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONGS_FAILURE = 'GET_SONGS_FAILURE';

export const DELETE_SONG = 'DELETE_SONG';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAILURE = 'DELETE_SONG_FAILURE';

export const EDIT_SONG = 'EDIT_SONG';
export const EDIT_SONG_SUCCESS = 'EDIT_SONG_SUCCESS';
export const EDIT_SONG_FAILURE = 'EDIT_SONG_FAILURE';

export const SET_SONG_STATUS = 'SET_SONG_STATUS';

//playlists

export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_FAILURE = 'GET_SONGS_FAILURE';

export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const ADD_PLAYLIST_SUCCESS = 'ADD_PLAYLIST_SUCCESS';
export const ADD_PLAYLIST_FAILURE = 'ADD_PLAYLIST_FAILURE';

export const CREATE_PLAYLIST_TABLE = 'CREATE_PLAYLIST_TABLE';
export const CREATE_PLAYLIST_TABLE_SUCCESS = 'CREATE_PLAYLIST_TABLE_SUCCESS';
export const CREATE_PLAYLIST_TABLE_FAILURE = 'CREATE_PLAYLIST_TABLE_FAILURE';

export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_FAILURE = 'DELETE_PLAYLIST_FAILURE';