export const GREEN = '#30C169'

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const CREATE_TABLES = 'CREATE_TABLES';
export const CREATE_TABLES_SUCCESS = 'CREATE_TABLES_SUCCESS';
export const CREATE_TABLES_FAILURE = 'CREATE_TABLES_FAILURE';

export const ADD_SONG = 'ADD_SONG';
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS';
export const ADD_SONG_FAILURE = 'ADD_SONG_FAILURE';

export const CLEAR_CHANGED = 'CLEAR_CHANGED';
export const SELECT_SONG = 'SELECT_SONG';

export const GET_SONGS = 'GET_SONGS';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONGS_FAILURE = 'GET_SONGS_FAILURE';

export const DELETE_SONG = 'DELETE_SONG';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAILURE = 'DELETE_SONG_FAILURE';

export const EDIT_SONG = 'EDIT_SONG';
export const EDIT_SONG_SUCCESS = 'EDIT_SONG_SUCCESS';
export const EDIT_SONG_FAILURE = 'EDIT_SONG_FAILURE';